name: Build GUI exe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        spec: gui.spec
        path: gui

    - uses: actions/upload-artifact@v4
      with:
        name: config-tool
        path: gui/dist/windows/YuanCon-CFWConfig.exe
